baseURL = "https://risotto.joeroe.io"
theme = "risotto"
title = "Astaroth"
author = "Joe Roe"
copyright = "© [Joe Roe](https://joeroe.io) & [risotto contributors](https://github.com/joeroe/risotto/graphs/contributors)."
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]

sectionPagesMenu = "journal"

[params]
noindex = false

[params.theme]
palette = "tokyo-night-dark"

[params.about]
title = "Astaroth"
description = "I think, therefore, I get brain smash"
logo = "images/rice.svg"

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/Astahjmo"


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "journalctl"
    name = "Journal"
    url = "/posts/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true

[markup]

  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true
